In [3]:
import numpy
database=[["abhi",6,60],["rahul",2,20],["harry",7,70],["Krish",8,80]]
ds=numpy.array(database)
type(ds)

numpy.ndarray

In [7]:
ds[:][2]

array(['harry', '7', '70'], dtype='<U5')

In [8]:
ds

array([['abhi', '6', '60'],
       ['rahul', '2', '20'],
       ['harry', '7', '70'],
       ['Krish', '8', '80']], dtype='<U5')

In [12]:
marks=ds[:,2]
marks

array(['60', '20', '70', '80'], dtype='<U5')

marks.sum()

In [14]:
marks.dtype=n

NameError: name 'n' is not defined

In [15]:
ds

array([['abhi', '6', '60'],
       ['rahul', '2', '20'],
       ['harry', '7', '70'],
       ['Krish', '8', '80']], dtype='<U5')

In [16]:
marks=[60,20,70,80]
hours=[6,2,7,8]
import numpy
marks=numpy.array(marks)
hours=numpy.array(hours)

In [17]:
marks

array([60, 20, 70, 80])

In [18]:
hours

array([6, 2, 7, 8])

In [19]:
type(marks)

numpy.ndarray

In [20]:
type(hours)

numpy.ndarray

In [21]:
marks=[60,20,70,80]
hours=[6,2,7,8]
import numpy
marks=numpy.array(marks)
hours=numpy.array(hours)
hours=hours.reshape(-1,1)


In [22]:
hours

array([[6],
       [2],
       [7],
       [8]])