In [1]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('sample.csv')
dataset

OTT  hours
0     2    7.0
1     4    7.0
2     2    7.0
3     2    8.0
4     1    8.0
5     3    6.3
6     2    7.0
7     1    6.0
8     5    7.0
9     2    7.0
10    6    6.0
11    4    7.0
12    1    8.0
13    4    7.0
14    4    7.0
15    5   11.0
16    2    8.0
17    2    7.0
18    1    8.0
19    2    7.0
20    2    8.0
21    2    8.0
22    3    8.0
23    1    7.0
24    2    6.0
25    4    6.0
26    1    5.0
27    2    8.0
28    1    8.0
29    1    7.0
30    4    9.0
31    4    6.0
32    0    6.0
33    0    6.0
34    0    6.0
35    0    8.0
36    0    8.0
37    0    8.0
38    8    4.0
39    6    4.0
40    9    3.0
41    9    4.0
42   10    3.5

In [2]:
y=dataset['hours']
x=dataset['OTT']
#typeacsting x from series to array
x=x.values
x=x.reshape(-1, 1)
type(x)

numpy.ndarray

In [3]:
y

0      7.0
1      7.0
2      7.0
3      8.0
4      8.0
5      6.3
6      7.0
7      6.0
8      7.0
9      7.0
10     6.0
11     7.0
12     8.0
13     7.0
14     7.0
15    11.0
16     8.0
17     7.0
18     8.0
19     7.0
20     8.0
21     8.0
22     8.0
23     7.0
24     6.0
25     6.0
26     5.0
27     8.0
28     8.0
29     7.0
30     9.0
31     6.0
32     6.0
33     6.0
34     6.0
35     8.0
36     8.0
37     8.0
38     4.0
39     4.0
40     3.0
41     4.0
42     3.5
Name: hours, dtype: float64

In [4]:
y

0      7.0
1      7.0
2      7.0
3      8.0
4      8.0
5      6.3
6      7.0
7      6.0
8      7.0
9      7.0
10     6.0
11     7.0
12     8.0
13     7.0
14     7.0
15    11.0
16     8.0
17     7.0
18     8.0
19     7.0
20     8.0
21     8.0
22     8.0
23     7.0
24     6.0
25     6.0
26     5.0
27     8.0
28     8.0
29     7.0
30     9.0
31     6.0
32     6.0
33     6.0
34     6.0
35     8.0
36     8.0
37     8.0
38     4.0
39     4.0
40     3.0
41     4.0
42     3.5
Name: hours, dtype: float64

In [5]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

model.predict([[8.0]])


array([5.09806495])

model.fit(x,y)

In [6]:
yhat=model.predict(x)

In [7]:
#BIAS y=mx+c      c=bias
m=model.coef_
m

array([-0.33446912])

In [8]:
c=model.intercept_
c

7.773817937068821

In [9]:
import joblib
joblib.dump(model , 'OTT.pk1')

['OTT.pk1']

In [10]:
from sklearn import metrics
metrics.mean_absolute_error(y,yhat)

0.9058924120227432

In [11]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)

In [17]:
model=LinearRegression()
#training
model.fit(X_train,y_train)


LinearRegression()

In [18]:
X_test

array([[0],
       [2],
       [4],
       [0],
       [0],
       [6],
       [1],
       [1],
       [5]], dtype=int64)

In [19]:
model.predict([[0]])

array([7.83853937])

In [20]:
y_test

37    8.0
24    6.0
25    6.0
36    8.0
34    6.0
39    4.0
4     8.0
12    8.0
8     7.0
Name: hours, dtype: float64